### ISSUE TITLE
Consider adding the Consensus Client when user sets fullnode in Ethereum repository

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#1149]
The Ethereum repository has 3 options: Remote, Light client and Full node

- Consider removing Light client option
- When using full node, consider adding the consensu client option so execution clients can get synced

**Comment by alexpeterson91** [comment]
Good issue, i cant count the amount of support cases i've had where people choose a full client and complain their node is broken because it wont sync, but they post logs that clearly say no CL client connected, and the getting started (which i'm finding is not a really a great place to share critical package info i.e. update notes (despite it being really important for notes on new and updated packages) because many users just close it before reading). I personally wrote the warnings and notes in all the clients that post merge each EL **NEEDs** to be connected to a CL to fully sync and vice-versa, im just shocked at how many cases I've had to deal with this when it's extremely clear in the UI already, so many people are just incapable of reading things, so I think I'm in favor of it automatically prompting you to install a CL at the same time.

I also strongly support removing the light client option, it doesn't work for a repo client, doesnt work with CLs, and i can't think of a situation light geth is ever useful post-merge.

**Comment by pablomendezroyo** [comment]
High priority then
