### ISSUE TITLE
Add consensus client to `runEthClientInstaller`

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#1256]
Complementary of https://github.com/dappnode/DNP_DAPPMANAGER/pull/1153

Review all the logic that handles the Execution Client status and add the Consensus Client to it

**Comment by dsimog01** [comment]
In system>repo>eth, if you have full node there is deaomon that install the selected clients. The part of the CC is not implemented. 

This involves thuinking about is we want this to be like that. 

If you remove Geth manually, it will be installed again. We could show a banner that tells the user to install Geth instead of doing it automatically. We could use remote sync while one client of the full node is not installed

**Comment by pablomendezroyo** [comment]
Added
