### ISSUE TITLE
Persist previous Eth repository config when switching to remote

### ISSUE THREAD

**Issue by dsimog01** [dappnode/DNP_DAPPMANAGER#1321]
Currently, when switching the Ethereum repository from local to remote, causes the local config to be set up to Geth+Prysm which are the first options of the drop down menu. It could be great to keep the last config the user has had, in order to restore it when they switch back to local repository.

**Comment by alexpeterson91** [comment]
This is still occurring. Shouldn't the Fix be relatively straightforward?  When switching from remote to full node in the repo page it should pull the global envs for mainnet EL and CL and set the enum drop-down to match the global envs. If there are no global envs set for mainnet it should display as it does now, just selecting the first entry in each enum. 

Or simpler just display the mainnet EL and CL global envs on the repo page all the time. Kinda like the status page of the stakers UI. But just show the current mainnet envs. 

So you don't accidentally select the wrong client and mess up your sync, which is becoming a harder and harder issue to come back from, just because you switched to a non local repo temporarily (for example while troubleshooting issues with updates) and you're still using your local node just not for the purpose of scanning the contracts for updates.
