### ISSUE TITLE
Add global env DEFAULT_FEE_RECIPIENT_{NETWORK}

### ISSUE THREAD

**Issue by dsimog01** [dappnode/DNP_DAPPMANAGER#1371]
Add a global env for the default fee recipient that should be set in the stakers UI(?). It will be set as fee recipient in case the user adds a new validator keystore to the signer with no fee recipient set. This will only apply for solo staking for the moment

**Comment by alexpeterson91** [comment]
Do you plan on doing this for all 3 stakersUIs?  Just curious. Also to clarify do you propose setting the default fee recipient address in the stakersUI? Since on initial setup most people set their mainnet EL and CL via the repo nav tab now correct?  So maybe it should be able to be set from the repo page and the stakers UI page?
Or is it something we just add into the onboarding flow/process during install. Just how we should have the option to set IPFS profile settings during install for cloud usage.

**Comment by pablomendezroyo** [comment]
> Since on initial setup most people set their mainnet EL and CL via the repo nav tab now correct? So maybe it should be able to be set from the repo page and the stakers UI page?

Nice feedback, I think if set in the repo tab it breaks with the rest of things that are out there. Makes more sense to have it in the stakers UI, maybe on another location, different than the consensus client card

**Comment by dsimog01** [comment]
If the EC <-> CC combination is set in the repository settings, I do not think it is necessary to set the fee recipient there, because there will not be any validators active. However, we need to be sure that no consensus client package is breaking due to not including a default fee recipient address
