### ISSUE TITLE
Lodestar integration in Stakers

### ISSUE THREAD

**Issue by dsimog01** [dappnode/DNP_DAPPMANAGER#1422]
In order to integrate Lodestar in each of the networks, we need to perform the following tasks:

1. Add Lodestar Team PK to dappmanager
- [x] Merge PR (https://github.com/dappnode/DNP_DAPPMANAGER/pull/1387)
- [x] Publish Core with this update

2. PRATER
- [x] Check client/signer compatibility

|  | PR created | PR merged | PKG published | Lodestar-compatible version | Tested compatibility |
|---|---|---|---|---|---|
| Besu | ✔️  | ✔️  | ✔️ | 0.1.1 |  ✔️  |
| Erigon | ✔️ | ✔️ | ✔️ | 0.1.5 |  ✔️  |
| Nethermind | ✔️ | ✔️ | ✔️ | 1.0.8 |  ✔️  |
| Geth | ✔️ | ✔️ | ✔️ | 0.4.28 |  ✔️  |
| Web3Signer | ✔️ | ✔️ | ✔️  | 0.1.18 (When published) |   ✔️  |

- [x] Check stakers compatibility with package versions in dappmanager backend (https://github.com/dappnode/DNP_DAPPMANAGER/pull/1388)
- [x] Publish lodestar
- [x] Add lodestar to stakers (https://github.com/dappnode/DNP_DAPPMANAGER/pull/1389/files)
- [x] Publish Core

3. MAINNET
- [x] Check client/signer compatibility

|  | PR created | PR merged | PKG published | Lodestar-compatible version | Tested compatibility |
|---|---|---|---|---|---|
| Besu | ✔️  | ✔️  | ✔️  | 1.2.7 |  ✔️ |
| Erigon | ✔️  | ✔️  | ✔️  | 0.1.38 |  ✔️ |
| Nethermind | ✔️  | ✔️  | ✔️  | 1.0.35 |  ✔️  |
| Geth | ✔️  | ✔️  | ✔️  | 0.1.38 | ✔️ |
| Web3Signer | ✔️  | ✔️  | ✔️  | 2.0.0 |   ✔️  |

- [x] Check stakers compatibility with package versions in dappmanager backend
- [x] Publish lodestar
- [x] Add lodestar to stakers
- [x] Publish Core

4. GNOSIS
- [x] Check client/signer compatibility

|  | PR created | PR merged | PKG published | Lodestar-compatible version |
|---|---|---|---|---|
| Erigon | ✔️  | ✔️  | ❌  | 0.1.0 (When published) |
| Nethermind | ✔️  | ✔️  |   ✔️  | 1.0.29 |
| Web3Signer | ✔️  | ✔️  |  ✔️  | 1.0.1 |

- [x] Check stakers compatibility with package versions in dappmanager backend
- [x] Publish lodestar
- [x] Add lodestar to stakers
- [x] Publish Core

**Comment by alexpeterson91** [comment]
I went ahead and marked all the things ive done to prep already, as you can see almost all of it is already published with the exception of mainnet and gnosis Web3Signers.  Apparently the github project i started 6 months ago to prep for lodestar was private until today and i added the team because i had a lot of this tracked before and couldn't understand why no one used or referred to my open project and just kept making new issues to track things i was already, so i gave up on it , only now realizing I was the only one who could ever see the project and how many issues and PRs were and are associated with it.

But yeah i prepped all the ELs for lodestar a while ago and all have been published already.
Even the web3signer for prater is ready and was published a month ago and has has another release since then.


 When we finish the signers up we need to fix/merge the teku certificate issue on the mainnet and gnosis web3signers so we can finally update the Teku mainnet and Gnosis packages, theyre like 5 months out of date (upstream) now and really need to be updated; not to distract from lodestar but we should do those changes to the signers at the same time.

**Comment by dsimog01** [comment]
Lodestar has been successfully integrated!
