### ISSUE TITLE
Remove `dns` from existing compose files and from the pkg installer

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#1608]
Depends on https://github.com/dappnode/DNP_DAPPMANAGER/pull/1589 and https://github.com/dappnode/DNP_DAPPMANAGER/pull/1588

Once the docker aliases migration is done, dappnode packages should not require anymore to have the BIND package as DNS server and the functionality `setDappnodeComposeDefaults` should not write anymore the DNS on new packages isntalled

**Comment by dappnodedev** [comment]
The actions to be made in order to remove the bind as DNS server are:

1. Publish the dappmanager (and core) with a migration that removes all the bind as `dns` from the `docker-compose` files of all the installed packages -> https://github.com/dappnode/DNP_DAPPMANAGER/pull/1646
2. Wait for some time so that the users and the auto updates can trigger the restart of the packages. When the containers are restarted, they will get the new configuration (i.e. they are not using bind as DNS server anymore)
3. Publish a new dappmanager (and core) removing the `nsupdate` module and doing `docker compose up` of all the packages (doing directly up will only restart those that have a new configuration) -> https://github.com/dappnode/DNP_DAPPMANAGER/pull/1645
4. Publish the new bind -> https://github.com/dappnode/DNP_BINDv2
