### ISSUE TITLE
Scripts to run in host

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#462]
We should consider running a selected list of commands useful for users:

### Implement next
- [x] Security updates https://github.com/dappnode/DNP_DAPPMANAGER/issues/745
- [ ] Install missing firmware: https://github.com/dappnode/DNP_DAPPMANAGER/issues/763
- [x] change ssh port: https://github.com/dappnode/DNP_DAPPMANAGER/pull/491
- [x] apt upgrade: https://github.com/dappnode/DNP_DAPPMANAGER/pull/959
- [x] update docker https://github.com/dappnode/DNP_DAPPMANAGER/pull/626
- [x] update docker-compose https://github.com/dappnode/DNP_DAPPMANAGER/pull/626
- [ ] manage, enable, disable the Firewall
- [ ] UFW (complicated firewall), FailToBan
    - Consider using [fail2band dockerized](https://github.com/crazy-max/docker-fail2ban) as a new dappnode package, exposing and API
    - Consider using an NGNIX proxy server instead

### Require more research
- [x] update distro? https://github.com/dappnode/DNP_DAPPMANAGER/issues/695
- [ ] install NTP?

**Comment by eduadiez** [comment]
Added issue related to `apt upgrade` https://github.com/dappnode/DAppNode/issues/263

**Comment by pablomendezroyo** [comment]
In order to have a better organization in the UI, I suggest:

place the following at **System > advanced**:
 - apt upgrade
 - update docker
 - update docker-compose

place the following at **System > security**:
 - manage, enable, disable the Firewall
 - UFW (complicated firewall), FailToBan
 - SSH enable/disable/change ports (REPLACE IT FROM ADVANCED)

**Comment by pablomendezroyo** [comment]
Related to **update docker** script:

There are several things to take into account.

###Current situation of docker in dappnode: 
According to [docker official docs installation for debian](https://docs.docker.com/engine/install/debian/#install-from-a-package), docker can be installed in three different ways:
1. Using docker repositories: **not available for the Debian buster 10 we are currently using in dappnode**
2. Manually with DEB package: the method we are currently using to install docker in dappnode
3. Script: not suitable

###Versioning problems
There is well known that you must be careful when updating docker. There have been already users that manually updated docker and it was incompatible with the Debian version they have. Examples are in our forum: [example 1](https://forum.dappnode.io/t/container-not-running-solved/795), [example 2](https://forum.dappnode.io/t/updated-os-via-ssh-docker-and-wifi-down-no-connection/850), [example 3](https://forum.dappnode.io/t/containers-not-running-debian-5-10-4-1-docker-less-than-20-10-2/797).

Also, according with their docs:
```
Got multiple Docker repositories?

If you have multiple Docker repositories enabled, installing or updating without specifying a version in the apt-get install or apt-get update command always installs the highest possible version, which may not be appropriate for your stability needs.
```

(BTW this might be related to the issue of [docker grafana dashboards](https://forum.dappnode.io/t/no-usage-metrics-for-docker-resource-usage/831))

###Why update docker?
Because of the info provided I consider it is not a good idea to allow users to have the option of update docker by themselves. This might cause more problems than resolutions.

Another option could be to allow users to update to a specific version of docker, this would allow users to go back to an older docker version if the one they installed did not work.

**Comment by pablomendezroyo** [comment]
Final solution: allow users to update docker through the UI with a **docker version hardcoded that is stable for dappnode**

**Comment by pablomendezroyo** [comment]
Consider defining scripts in GitHub and make the dappmanager to pull them when attemping to use them. This would allow editing the script without the necessity to do a new release

**Comment by dapplion** [comment]
> Consider defining scripts in GitHub and make the dappmanager to pull them when attemping to use them. This would allow editing the script without the necessity to do a new release
> 
> Update: may be dangerous

All of DAppNode's updates (specially this critically sensitive part) must be distributed through decentralized independently-verifiable channels: IPFS + Aragon Package Manager (APM) smart contracts in Ethereum Mainnet.

**Comment by pablomendezroyo** [comment]
_Consider using an NGNIX proxy server instead_

@3alpha we are currently using HTTPs as proxy right

**Comment by 3alpha** [comment]
We use it as a proxy just to local network.

**Comment by alexpeterson91** [comment]
@dapplion hey guys there's an issue with the newest NUC11 Wi-Fi card drivers. They have the firmware support as of kernel version 5.10.x + which the ISO install had, but the firmware files specifically one necessary to make it work even on startup gets moved to the wrong place but running `apt-get upgrade` can and does move the file to the wrong spot and the computer can't even find the interface. It's a well documented bug and there's a one liner fix but the info I found was that the cause is just running `apt-get upgrade` so this other one line command moving the file back is needed along with a reboot to activate the firmware after an upgrade. So we might be shooting ourselves in the foot here if we plan on selling NUC11s soon and there's this known issue already. There's also an issue with Bluetooth needing to be disabled in the firmware to even log into the console after the first boot of the OS. I still need to investigate the cause of that further. 
But mainly just wanted to make sure everyone knows there's an issue with the new NUC11 Wi-Fi card firmware being broken by running `apt-get upgrade`

**Comment by dapplion** [comment]
> @dapplion hey guys there's an issue with the newest NUC11 Wi-Fi card drivers. They have the firmware support as of kernel version 5.10.x + which the ISO install had, but the firmware files specifically one necessary to make it work even on startup gets moved to the wrong place but running `apt-get upgrade` can and does move the file to the wrong spot and the computer can't even find the interface. It's a well documented bug and there's a one liner fix but the info I found was that the cause is just running `apt-get upgrade` so this other one line command moving the file back is needed along with a reboot to activate the firmware after an upgrade. So we might be shooting ourselves in the foot here if we plan on selling NUC11s soon and there's this known issue already. There's also an issue with Bluetooth needing to be disabled in the firmware to even log into the console after the first boot of the OS. I still need to investigate the cause of that further. But mainly just wanted to make sure everyone knows there's an issue with the new NUC11 Wi-Fi card firmware being broken by running `apt-get upgrade`

CC: @eduadiez @3alpha @pablomendezroyo

**Comment by pablomendezroyo** [comment]
> @dapplion hey guys there's an issue with the newest NUC11 Wi-Fi card drivers. They have the firmware support as of kernel version 5.10.x + which the ISO install had, but the firmware files specifically one necessary to make it work even on startup gets moved to the wrong place but running `apt-get upgrade` can and does move the file to the wrong spot and the computer can't even find the interface. It's a well documented bug and there's a one liner fix but the info I found was that the cause is just running `apt-get upgrade` so this other one line command moving the file back is needed along with a reboot to activate the firmware after an upgrade. So we might be shooting ourselves in the foot here if we plan on selling NUC11s soon and there's this known issue already. There's also an issue with Bluetooth needing to be disabled in the firmware to even log into the console after the first boot of the OS. I still need to investigate the cause of that further. But mainly just wanted to make sure everyone knows there's an issue with the new NUC11 Wi-Fi card firmware being broken by running `apt-get upgrade`

pleas, could you provide more detailed information? name of the driver, the wrong paths, the upstream iussue...

**Comment by alexpeterson91** [comment]
ok so i figured out the NUC 11 wifi firmware issue and got it to work now, i havent checked to see if the bluetooth was resolved by it too, some people said they are related, but the issue is complicated for the WiFi.  It seems that the adapter in the NUC im using (its a top end model with a WiFi 6E NVMe card Intel Wi-Fi 6E AX210(Gig+)) which is probably not in all new NUCs but it definitely will be (unless we skip wifi6E and go right to wifi 7 due to the global chip shortage)  anyways this adapter should actually be supported in kernel versions above 5.10 which my install is/was so i kept looking, found that theres some issue where the files get moved around when running apt-get upgrade etc, and this command `sudo mv /usr/lib/firmware/iwlwifi-ty-a0-gf-a0.pnvm  /usr/lib/firmware/iwlwifi-ty-a0-gf-a0.bak` needs to be run periodically and then the NUC must be rebooted and suddenly itll work. https://askubuntu.com/a/1360291 had the answer with the bug profiled here https://bugzilla.kernel.org/show_bug.cgi?id=212371#c13

**Comment by pablomendezroyo** [comment]
> ok so i figured out the NUC 11 wifi firmware issue and got it to work now, i havent checked to see if the bluetooth was resolved by it too, some people said they are related, but the issue is complicated for the WiFi. It seems that the adapter in the NUC im using (its a top end model with a WiFi 6E NVMe card Intel Wi-Fi 6E AX210(Gig+)) which is probably not in all new NUCs but it definitely will be (unless we skip wifi6E and go right to wifi 7 due to the global chip shortage) anyways this adapter should actually be supported in kernel versions above 5.10 which my install is/was so i kept looking, found that theres some issue where the files get moved around when running apt-get upgrade etc, and this command `sudo mv /usr/lib/firmware/iwlwifi-ty-a0-gf-a0.pnvm /usr/lib/firmware/iwlwifi-ty-a0-gf-a0.bak` needs to be run periodically and then the NUC must be rebooted and suddenly itll work. https://askubuntu.com/a/1360291 had the answer with the bug profiled here https://bugzilla.kernel.org/show_bug.cgi?id=212371#c13

then I would move this issue onto the DNP_WIFI repository, it has the docker socket volume so we can run such commands to rename in the paths

**Comment by pablomendezroyo** [comment]
Completed the required tasks
