### ISSUE TITLE
VPN Open Port check to be integrated into auto-diagnose tab of the dashboard 

### ISSUE THREAD

**Issue by alexpeterson91** [dappnode/DNP_DAPPMANAGER#594]
**Is your feature request related to a problem? Please describe.**
Yes, upon completing initial setup in the dashboard over Wi-Fi connection to the dappnode, there are several things checks done by the software to check the status of various systems which is the first sight of the auto diagnose tab in system. One of these checks performed is regarding checking if ports are open or if UPnP is enabled. This check is the issue as it does not properly address a large portion of home users with off the shelf or worse ISP provided routers.  A vast majority of home routers also have an issue with their implementation of UPnP where it works in most cases but not all. I first found while this spinning up dozens of the bitcoind/Bitcoin core nodes going back to at least 2013. 

The issue is that this check does not actually check if the needed ports are open for all of the system services. The most important being, at least in setup, the VPN needed to connect and control the dappnode securely and remotely. These ports in particular are UDP:1194
TCP:8092
When this doesn’t happen it has manifested as at least half a dozen people asking the same question in the support and setup support channels on Discord in under a week. 
**Describe the solution you'd like**

I would propose that those 2 ports 
UDP:1194
TCP:8092
, due to their importance in the early and all following stages such as maintenance, developing, and even just letting it run on the rack/shelf/desk to check dashboards occasionally, be specifically added to the startup checks snd the system auto diagnose system to confirm the ports allow traffic through. 
**Describe alternatives you've considered**

Alternatively if this consumes too many resources or relies on to many other services that can fail to check this port configuration then even a simple note added to the UI during initial setup and also on the system auto diagnose tab for you to manually check and open those ports 
UDP:1194
TCP:8092
specifically, on your router if experiencing VPN issues. 
I’ve also found that in some cases other routers can work snd open the ports sometimes over UPnP but then stop somewhat spontaneously and need to be opened manually. So making sure this note is included in documentation and the UI would be most helpful for users. 
**Additional context**

My dappnode is currently with DHL in Spain as I write this about to be exchanged so I have no screenshots to share right now.

**Comment by pablomendezroyo** [comment]
@alexpeterson91 Thank you so much for your well-documented issue.

I totally agree with you that these ports (8092 and 1194) sometimes are generating unnecessary support. Both solutions you propose are great, in my opinion should not be too hard to implement a check for those specific ports.

As a first approach I suggest:

**Comment by pablomendezroyo** [comment]
@alexpeterson91 Thank you so much for your well-documented issue.

I totally agree with you that these ports (8092 and 1194) sometimes are generating unnecessary support. Both solutions you propose are great. In my opinion, should not be too hard to implement a check for those specific ports.

As a first approach I suggest:

- Configure the **dappmanager** container to have preinstalled whatever tools for networking, such as the well-known **nmap**.
- Implement the necessary logic in the **dappmanager** to do these ports mapping
- Execute these ports check whenever rendering the **support > autodiagnose** page
- Returns to the user a better correct/error message when ports are opened/closed.

Requirements would be:
- Host local IP: is not a problem in the new version since it is refreshed and exposed by the API.
- Networking tool (e.g nmap)
- Ports to be mapped (8092, 1194)

**Comment by dapplion** [comment]
@pablomendezroyo Is this issue solved or partially resolved with your port check service?

**Comment by alexpeterson91** [comment]
I mean the issue all along was just UPnP not opening all the ports needed specifically the UDP and TCP VPN ports. But successfully opening every other port needed to function. I fixed it just by port forwarding the 2 ports in my router manually and setting a DHCP reservation for my dappnode on my router so that it always kept the right ports forwarded for the VPN service. I keep seeing people post about not being able to connect and at least 25%-50% of the time there are posts from newcomers on discord about the VPN not being accessible from outside the network it’s because those ports are not properly forwarded.

**Comment by pablomendezroyo** [comment]
@dapplion yes! I would say this issue can be closed with the view of the port

@alexpeterson91 regarding the UPnP not opening all the ports, is something out of the scope of DAppNode. We are not able to manage how every single router works since each of them has different specifications and works in a different way. Anyway there will be a view for ports status where you would be able to check which ports needs to be opened, its status (open or closed), the port protocol, and which service will use that port

**Comment by alexpeterson91** [comment]
And that view check was exactly the feature I requested anyway, I know all networks are different so just knowing whether its open or not is enough for this for sure.

**Comment by pablomendezroyo** [comment]
#609 closes
