### ISSUE TITLE
DynDNS may take too long to be set up on dappmanager

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#877]
### ISSUE
When installing Dappnode from scratch, trying to get Wireguard credentials to result in an empty endpoint 

The issue may be:
- DYNDNS takes too long to be configured
- dyndnsDaemon in dappmanager is configured incorrectly so it takes too long to get creds

### UPDATE
Even having DYNDNS shown in the UI the command `dappnode_wireguard` still shown empty endpoint 

### UPDATE 2
The issue seems to be related to a time delay configured by wireguard to get the DYNDNS: https://github.com/dappnode/DNP_WIREGUARD/blob/18f75e4048acf51c9c5840b95a7256e1f270f3df/root/etc/cont-init.d/30-config#L249

The time delay is up to 40 seconds to retrieve the dyndns endpoint from the dappmanager API. If this endpoint does not exist the configuration file will contain an empty endpoint.

Approaches:
- Increase delay to retrieve the dyndns
- Set public IP if dyndns does not exist yet
- Throw error if no dyndns and public IP exist

**Comment by 3alpha** [comment]
At first, setting public IP seems sensible, but I don't know whether it is a good approach. It will generate configuration file which works for a while and it will make a false sense that everything is fine. Problem is when it stops working because IP has changed, users may lose their access to dappnode.

**Comment by pablomendezroyo** [comment]
Agree.

I would suggest:
- [ ] Detect average time to get dyndns from dappmanager when installing from scratch. Dappmanager has a few processes on startup so it can take a while..
- [ ] Set this time with a safety increase to the actual time delay in the wireguard container
- [ ] Even if this delay does not work set the public IP.
- [ ] If the public IP is used, start a daemon in background to get the dyndns and when it exist update the config file and stop the daemon
- [ ] Lastly inform the user somehow that he/she got the "temporary" credentials when using public IP

**Comment by 3alpha** [comment]
I agree.

About last three points, maybe it would be best to implement that logic in startup scripts which actually print QR/conf files because leaving empty field is the easiest way to communicate that something's not right. Also, for any other subsequent peer addition if field is empty, additional try to fetch DYNDNS is done by add-peers script. Thoughts?

**Comment by pablomendezroyo** [comment]
Yes nice catch, actually there are two places where the credentials are retrieved:
- UI: at **VPN > Wireguard > credentials**
- CLI: with `dappnode_wireguard` its executed a static script

The critical path is that this is the **onboarding** user experience of a user into dappnode, if the user tries to connect to dappnode for the first time through Wireguard and it does not work it would be bad. User should be able to connect to dappnode at any price when they are on the onboarding process

**Comment by 3alpha** [comment]
I agree it is critical that it works out of the box. 

Since these config files are very readable, maybe if we encounter error `Endpoint = ` is empty during onboarding step we should printout detailed reason why printed config file is temporary, what `Endpoint` directive means, and instruct user either to manually edit it or to generate new config file from dappmanager UI. Config files generated from UI should always work because then we know dappmanager is up and should serve `my.dappnode/global-envs/HOSTNAME` endpoint.

**Comment by pablomendezroyo** [comment]
To summarize:
- After knowing the average time to get dyndns and update the delay on the wireguard side this should be a weird edge case
- Wireguard credentials from the UI should always have endpoint set to the existing dyndns. This carries another issue: https://github.com/dappnode/DNP_DAPPMANAGER/issues/882
- Wireguard credentials from the CLI may contain endpoint with public IP, there should be shown a beauty message indicating that this should be something temporary. This carries another issue: https://github.com/dappnode/DNP_WIREGUARD/issues/18
- Wireguard `add_peers` execution should have a greater deleay to wait for dynds to exist on the dappmanager. This carries another issue: https://github.com/dappnode/DNP_WIREGUARD/issues/17

@3alpha thoughts?

**Comment by pablomendezroyo** [comment]
Closing this as considered as complete
