### ISSUE TITLE
Eth2.0: Validator migration

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#916]
## Description 
In the upcoming [Eth2.0 multiclients](https://github.com/dappnode/DAppNode/issues/329) support in DAppNode there is expected to be more than 1 Eth2 validator available in the dappstore. Users will be able to switch between Eth2 validators, so the dappmanager must be ready for this purpose.

## Migration
The Eth2 validator migration must be as smooth as possible so the user, ideally, with an update the user will switch from the current Prysm validator to the web3 signer, doing all the processes automatically in the background.

:warning: The validator migration must be done after ensuring not to run more than 1 validator at the same time:  https://github.com/dappnode/DNP_DAPPMANAGER/issues/913

The processes to automate the Eth2 validator migration in the background are:

### **Slashing protection (SP) data migration**
- :grey_question: **Prysm** 
```
validator slashing-protection export --datadir=/root/.eth2validators
```
- :x: Issue exporting slashing protection data: the SP is in the container volume, exporting with the container running results in an empty SP, might be due to the validator is using it so it cannot be exported unless the binary validator is stopped. When attempting to export with the validator stopped running a separate container with the same volume, it returns an error due to not connecting with the beacon chain. https://github.com/prysmaticlabs/prysm/issues/9897
- :grey_question: Is necessary to export + export the SP from the current validator to the web3 signer or is it enough to use the one created by the Web3 signer

### **Validator keys migration**
- :heavy_check_mark: **Prysm** 
```
# 1. Get public keys
validator accounts list --wallet-dir=/root/.eth2validators --wallet-password-file=/root/.eth2validators/walletpassword.txt
# 2. Backup
validator accounts backup --wallet-dir=/root/.eth2validators --wallet-password-file=/root/.eth2validators/walletpassword.txt --backup-dir=/root/ --backup-password-file=/root/pass.txt --backup-public-keys=  --prater
```
- :grey_question: differences between exporting and copying the `keystore.json` file: the `message` key contains a different value. There is one more key in the exporting file: `publicKey`
- :grey_question: What is the Keystore format used by the web3signer, can be used directly the validator docker volume to use the cleanest code possible

**Comment by dapplion** [comment]
## Flow to migrate from Prysm to Web3Signer + Prysm

`prysm.dnp.dappnode.eth` will have a major update to signal this breaking change.

The rough installation procedure done atomically by the DAPPMANAGER will be:

1. Install Web3Signer
2. Stop validator container
3. Migrate slashing protection data
4. Migrate keys
5. Permanently delete validator container
6. Start Web3Signer
7. Update Prysm to the new version that that follows the Web3Signer
  7a. Delete `validator-data` and expect new version to create it again
  7b. Add ENV to point to Web3Signer endpoint

*The DAPPMANAGER must be able to recover this flow from any point*

```ts
function installPackage() {
  if (dnpName === "prysm" && currentVersion ~ 1 && nextVersion ~ 2) {
    // special flow
  } else {
    // regular install
  }
}
```

In the UI add the same logic that will display a banner with detailed info + "Don't do anything for at least N minutes" in the package installation page.

TODO:

- [ ] Test that auto-updates are NOT triggered with major updates
- [ ] Auth for keymanager? Does it need to be authenticated? What happens if a rogue container calls the keymanager?
- [ ] Does the Web3Signer has whitelisting? How to tell it to only serve a Prysm if both Prysm and Lighthouse request signatures?
- [ ] Bonus: How can this flow be generalized to other migrations if applicable?

**Comment by pablomendezroyo** [comment]
Implemented on the package side and not in the dappmanager
